name: Mirror to Personal Repo

on:
  push:
    branches: [ main ]

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      
      - name: Push to mirror
        uses: pixta-dev/repository-mirroring-action@v1
        with:
          # Change YOUR_USERNAME and YOUR_REPO_NAME to your actual personal github username and repository name
          target_repo_url: https://${{ secrets.PAT }}@github.com/YOUR_USERNAME/YOUR_REPO_NAME.git
          ssh_private_key: ''
